### ISSUE TITLE
All builds failed with 'AdoptOpenJDK/build-jdk/v1/action.yml (Line: 14, Col: 15): Unexpected value '''

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/build-jdk#10]
All builds failed with 'AdoptOpenJDK/build-jdk/v1/action.yml (Line: 14, Col: 15): Unexpected value '''

Happened from Aug 4th.

**Comment by smlambert** [comment]
@sophia-guo - do you know what the core issue is here?
