### ISSUE TITLE
nightly builds stopped since Jan 24th.

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/build-jdk#20]
nightly builds hasn't been triggered for 10 days. Could the usage limits be reached?

**Comment by smlambert** [comment]
I see this message:

<img width="1033" alt="Screen Shot 2021-02-04 at 2 04 12 PM" src="https://user-images.githubusercontent.com/2836948/106942229-ec260c00-66f1-11eb-8c6d-6bd59913c047.png">

**Comment by smlambert** [comment]
I have pressed the Enable workflow button.

**Comment by sophia-guo** [comment]
Looks like the scheduled jobs are still disabled.

**Comment by sophia-guo** [comment]
Comes back. Close it.
