### ISSUE TITLE
Update jdk15 to jdk16

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/build-jdk#21]
https://github.com/AdoptOpenJDK/build-jdk/blob/master/.github/workflows/nightly.yml#L13

**Comment by sophia-guo** [comment]
I have tried yesterday with jdk16u and noticed that https://github.com/AdoptOpenJDK/openjdk-jdk16u hasn't been available. Should we wait when it's available?

https://github.com/sophia-guo/runaqaTest/actions/runs/535307586

**Comment by sophia-guo** [comment]
A couple of issues:

1. we can support jdk16, i.e. if jdk16u is not available.  The cons is we might need to constantly switch between ` javaToBuild :jdk** ` and ` javaToBuild :jdk**u` in the nightly workflow file. 
2. jdk15+ get error like  `configure: error: Invalid value for --enable-jvm-feature-dtrace: 'auto'`,  https://github.com/AdoptOpenJDK/build-jdk/runs/1765281642?check_suite_focus=true .  Looks like from jdk15 we need to switch from `--enable-dtrace=auto` to `--enable-dtrace` https://github.com/openjdk/jdk/blob/master/make/autoconf/jvm-features.m4#L99.   Looks like openjdk-build set another layer to do those configuration `openjdk-build/build-farm/platform-specific-configurations`. For build-jdk we actually doesn't use this layer. If we use this layer the story will be different from developer's local story. If we don't use this layer we might need to continually do extra job to deal with those configuration.

**Comment by sophia-guo** [comment]
switch from --enable-dtrace=auto to --enable-dtrace and hit the error:
`configure: ERROR: Unavailable JVM features explicitly enabled for 'server': 'dtrace'`
https://github.com/sophia-guo/runaqaTest/runs/1866216897?check_suite_focus=true

while in adoptopenjdk build we can see the same configuration and `configure: Default JVM features explicitly enabled for 'server': 'dtrace'\nchecking JVM features to use for variant 'server'... '`  https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk16/job/jdk16-linux-x64-hotspot/45/console

**Comment by smlambert** [comment]
jdk16u is now available: https://github.com/openjdk/jdk16u

**Comment by 2001asjad** [comment]
Hi @smlambert I would like to work on this issue as I want to get started. Can you please guide me a bit more regarding this issue.
 like which files to look ?

**Comment by smlambert** [comment]
welcome @2001asjad ! 

Please start by updating https://github.com/AdoptOpenJDK/build-jdk/blob/master/.github/workflows/nightly.yml#L13 
from :
`javaToBuild: [jdk11u, jdk15u]` 
to :
`javaToBuild: [jdk11u, jdk16u]`

I believe when you create and push to your PR it will trigger a build that will test your change.

@sophia-guo can further advise if there are other changes required.

**Comment by sophia-guo** [comment]
There is a similar commit to update from jdk14 to jdk15 https://github.com/AdoptOpenJDK/build-jdk/commit/41f233a4116de4e7145f5c93f61372bfcbecca6a. 

I believe you will hit some issue with the build for jdk16u but be relax the most probability is it has nothing with your change. We'll wait and see.

**Comment by 2001asjad** [comment]
@smlambert @sophia-guo Please review my PR and suggest the changes if required.
