### ISSUE TITLE
All but 3 build configurations are successful

### ISSUE THREAD

**Issue by Icohedron** [AdoptOpenJDK/build-jdk#23]
I ran the `AdoptOpenJDK/build-jdk@v1` GitHub action against all combinations of jdk versions `11,12,13,15`, platforms `ubuntu-latest,macos-latest,windows-latest`, and jdk implementations `hotspot,openj9`.
All but 3 of them were successful. See: [this github workflow run](https://github.com/Icohedron/openjdk-tests/actions/runs/630640656)

**Comment by sophia-guo** [comment]
[Updated jdk15 to jdk16 ](https://github.com/AdoptOpenJDK/build-jdk/pull/26) now 3 builds failed. Open the issue https://github.com/AdoptOpenJDK/build-jdk/issues/27, close this one.
