### ISSUE TITLE
Update workflows to build jdk15 instead of jdk14

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/build-jdk#9]
Now that jdk14 is 'done' and replaced with jdk15, we should update the workflow files.

**Comment by smlambert** [comment]
To update:
https://github.com/AdoptOpenJDK/build-jdk/blob/master/.github/workflows/test.yml#L19
and
https://github.com/AdoptOpenJDK/build-jdk/blob/master/.github/workflows/test.yml#L45

**Comment by sophia-guo** [comment]
Closed by #14
